### ISSUE TITLE
Fails to build with Qt5 5.12.10

### ISSUE THREAD

**Issue by darkshram** [lxqt/lxqt-config#734]
This is another `QStringView` issue:
```
[100%] Building CXX object lxqt-config-appearance/CMakeFiles/lxqt-config-appearance.dir/LXQtAppTranslationLoader.cpp.o
cd /builddir/build/BUILD/lxqt-config-0.17.1/i686-redhat-linux-gnu/lxqt-config-appearance && /usr/lib/ccache/c++ -DLXQT_CONFIG_VERSION=\"0.17.0\" -DLXQT_DATA_DIR=\"/usr/share\" -DLXQT_ETC_XDG_DIR=\"/etc/xdg\" -DLXQT_GRAPHICS_DIR=\"/usr/share/lxqt/graphics\" -DLXQT_MAJOR_VERSION=\"0\" -DLXQT_MINOR_VERSION=\"17\" -DLXQT_PATCH_VERSION=\"0\" -DLXQT_RELATIVE_SHARE_DIR=\"lxqt\" -DLXQT_RELATIVE_SHARE_TRANSLATIONS_DIR=\"lxqt/translations\" -DLXQT_SHARE_DIR=\"/usr/share/lxqt\" -DLXQT_SHARE_TRANSLATIONS_DIR=\"/usr/share/lxqt/translations\" -DLXQT_VERSION=\"0.17.0\" -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_NO_URL_CAST_FROM_STRING -DQT_SVG_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DQT_XML_LIB -I/builddir/build/BUILD/lxqt-config-0.17.1/i686-redhat-linux-gnu/lxqt-config-appearance -I/builddir/build/BUILD/lxqt-config-0.17.1/lxqt-config-appearance -I/builddir/build/BUILD/lxqt-config-0.17.1/i686-redhat-linux-gnu/lxqt-config-appearance/lxqt-config-appearance_autogen/include -I/usr/include/qt5/QtGui/5.12.10 -I/usr/include/qt5/QtGui/5.12.10/QtGui -I/usr/include/qt5/QtCore/5.12.10 -I/usr/include/qt5/QtCore/5.12.10/QtCore -I/builddir/build/BUILD/lxqt-config-0.17.1/lxqt-config-appearance/../liblxqt-config-cursor -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib/qt5/./mkspecs/linux-g++ -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtXml -isystem /usr/include/lxqt -isystem /usr/include/lxqt/LXQt -isystem /usr/include/KF5/KWindowSystem -isystem /usr/include/KF5 -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5xdg -isystem /usr/include/qt5xdgiconloader -isystem /usr/include/qt5xdgiconloader/3.7.0 -isystem /usr/include/qt5/QtSvg -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -fno-exceptions -Wall -Wextra -Wchar-subscripts -Wno-long-long -Wpointer-arith -Wundef -Wformat-security -Wnon-virtual-dtor -Woverloaded-virtual -Wpedantic -DNDEBUG -fPIE -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -std=c++14 -o CMakeFiles/lxqt-config-appearance.dir/LXQtAppTranslationLoader.cpp.o -c /builddir/build/BUILD/lxqt-config-0.17.1/i686-redhat-linux-gnu/lxqt-config-appearance/LXQtAppTranslationLoader.cpp
gmake[2]: Leaving directory '/builddir/build/BUILD/lxqt-config-0.17.1/i686-redhat-linux-gnu'
[100%] Built target lxqt-config-input
/builddir/build/BUILD/lxqt-config-0.17.1/lxqt-config-appearance/configothertoolkits.cpp: In member function 'void ConfigOtherToolKits::setGsettingsConfig(QString, QString)':
/builddir/build/BUILD/lxqt-config-0.17.1/lxqt-config-appearance/configothertoolkits.cpp:232:38: error: 'splitCommand' is not a member of 'QProcess'
         QStringList args = QProcess::splitCommand(QStringView(command));
                                      ^~~~~~~~~~~~
gmake[2]: *** [lxqt-config-appearance/CMakeFiles/lxqt-config-appearance.dir/build.make:381: lxqt-config-appearance/CMakeFiles/lxqt-config-appearance.dir/configothertoolkits.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: Leaving directory '/builddir/build/BUILD/lxqt-config-0.17.1/i686-redhat-linux-gnu'
gmake[1]: *** [CMakeFiles/Makefile2:613: lxqt-config-appearance/CMakeFiles/lxqt-config-appearance.dir/all] Error 2
gmake[1]: Leaving directory '/builddir/build/BUILD/lxqt-config-0.17.1/i686-redhat-linux-gnu'
gmake: *** [Makefile:152: all] Error 2
```
This is the related code. No clue (yet) how to make this work with Qt5 5.12.

![Captura de pantalla_2021-04-15_11-04-16](https://user-images.githubusercontent.com/10327500/114901654-a153ff00-9dda-11eb-915e-9efc006fee77.png)

So far this is my build order:

```
    lxqt-build-tools-0.9.0
    libqtxdg-3.7.0
    liblxqt-0.17.0
    libfm-qt-0.17.0
    lxqt-qtplugin-0.17.0
    libsysstat-0.4.5
    qtermwidget-0.17.0
    pcmanfm-qt-0.17.0
    lximage-qt-0.17.0
    lxqt-archiver-0.4.0
    lxqt-about-0.17.0
    lxqt-config-0.17.1 <-- I'm stuck here
    lxqt-globalkeys-0.17.0
    lxqt-notificationd-0.17.0
    lxqt-policykit-0.17.0
    lxqt-powermanagement-0.17.0
    lxqt-session-0.17.0
    lxqt-sudo-0.17.0
    lxqt-panel-0.17.0
    lxqt-runner-0.17.0
    lxqt-themes-0.17.0
    qterminal-0.17.0
    lxqt-openssh-askpass-0.17.0
    lxqt-admin-0.17.0
    pavucontrol-qt-0.17.0
    screengrab-2.2.0
    qps-2.3.0
```

**Comment by tsujan** [comment]
This is worse because `QProcess::splitCommand()` doesn't exist in Qt < 5.15 :(

**Comment by darkshram** [comment]
Will try to figure out a way using something like this:

`QProcess::execute(const QString &command));`

**Comment by tsujan** [comment]
> Will try to figure out a way using something like this: QProcess::execute(const QString &command));

It should start detached. Maybe the obsolete method `QProcess::startDetached(const QString &command)` should be used for Qt < 5.15. How? I still don't know because the app is `gsettings` and needs some arguments.

**Comment by tsujan** [comment]
@darkshram 

Try this (extra whitespaces were automatically removed by featherPad):
```diff
diff -ruNp lxqt-config-orig/lxqt-config-appearance/configothertoolkits.cpp lxqt-config/lxqt-config-appearance/configothertoolkits.cpp
--- lxqt-config-orig/lxqt-config-appearance/configothertoolkits.cpp	2021-04-09 02:47:29.000000000 +0430
+++ lxqt-config-20210409/lxqt-config-appearance/configothertoolkits.cpp	2021-04-15 21:10:36.162654418 +0430
@@ -93,7 +93,7 @@ set org.gnome.desktop.interface cursor-s
  * Button and menu images are deprecated in GTK 3.10:
  *    https://developer.gnome.org/gtk3/stable/GtkSettings.html#GtkSettings--gtk-menu-images
  * Toolbar-style is also deprecated.
- * GTK just doesn't intend to support image menu items. They're considered bad practice in modern UI. 
+ * GTK just doesn't intend to support image menu items. They're considered bad practice in modern UI.
  */
 
 ConfigOtherToolKits::ConfigOtherToolKits(LXQt::Settings *settings,  LXQt::Settings *configAppearanceSettings, QObject *parent) : QObject(parent)
@@ -227,10 +227,14 @@ void ConfigOtherToolKits::setGsettingsCo
     if(version == QLatin1String("3.0"))
         commands = getConfig(GTK3_GSETTINGS, ConfigOtherToolKits::GTK3GSETTINGS);
     for(QString command : commands.split(QStringLiteral("\n"))) {
-        if(command.isEmpty() or command.startsWith(QStringLiteral("#")))
+        if(command.isEmpty() || command.startsWith(QStringLiteral("#")))
             continue;
+#if (QT_VERSION >= QT_VERSION_CHECK(5,15,0))
         QStringList args = QProcess::splitCommand(QStringView(command));
         bool ok = QProcess::startDetached(QStringLiteral("gsettings"), args);
+#else
+        bool ok = QProcess::startDetached(QStringLiteral("gsettings ") + command);
+#endif
         if(!ok) {
             QMessageBox::critical((QWidget*) parent(), tr("Error"), tr("Error: gsettings cannot be run"));
             break;
@@ -308,7 +312,7 @@ QStringList ConfigOtherToolKits::getGTKT
 {
     QStringList themeList;
     QString configFile = version==QLatin1String("2.0") ? QStringLiteral("gtkrc") : QStringLiteral("gtk.css");
-    
+
     if(version != QLatin1String("2.0")) {
         // Insert default GTK3 themes:
         themeList << QStringLiteral("Adwaita") << QStringLiteral("HighContrast") << QStringLiteral("HighContrastInverse");

```
"gsettings " is added with a spaces after it.

**Comment by darkshram** [comment]
Thanks! Worked perfectly. Built without warnings. Final patch looks like this.
```
diff -Naur lxqt-config-0.17.1.orig/lxqt-config-appearance/configothertoolkits.cpp lxqt-config-0.17.1/lxqt-config-appearance/configothertoolkits.cpp
--- lxqt-config-0.17.1.orig/lxqt-config-appearance/configothertoolkits.cpp	2021-04-15 05:18:39.000000000 -0500
+++ lxqt-config-0.17.1/lxqt-config-appearance/configothertoolkits.cpp	2021-04-15 11:48:35.354365149 -0500
@@ -227,10 +227,14 @@
     if(version == QLatin1String("3.0"))
         commands = getConfig(GTK3_GSETTINGS, ConfigOtherToolKits::GTK3GSETTINGS);
     for(QString command : commands.split(QStringLiteral("\n"))) {
-        if(command.isEmpty() or command.startsWith(QStringLiteral("#")))
+        if(command.isEmpty() || command.startsWith(QStringLiteral("#")))
             continue;
+#if (QT_VERSION >= QT_VERSION_CHECK(5,15,0))
         QStringList args = QProcess::splitCommand(QStringView(command));
         bool ok = QProcess::startDetached(QStringLiteral("gsettings"), args);
+#else
+        bool ok = QProcess::startDetached(QStringLiteral("gsettings ") + command);
+#endif
         if(!ok) {
             QMessageBox::critical((QWidget*) parent(), tr("Error"), tr("Error: gsettings cannot be run"));
             break;
```

**Comment by tsujan** [comment]
Thanks for reporting and testing!
