### ISSUE TITLE
Fails to build with KDE Frameworks 5.103 and Plasma 5.27

### ISSUE THREAD

**Issue by jubalh** [lxqt/lxqt-config#919]
It appears that lxqt-config fails to build with KDE Frameworks 5.103 and Plasma 5.27:

```
[  176s] In file included from /usr/include/KF5/KScreen/KScreen/Config:1,
[  176s]                  from /home/abuild/rpmbuild/BUILD/lxqt-config-1.2.0/build/lxqt-config-monitor/lxqt-config-monitor_autogen/EWIEGA46WW/../../../../lxqt-config-monitor/fastmenu.h:28,
[  176s]                  from /home/abuild/rpmbuild/BUILD/lxqt-config-1.2.0/build/lxqt-config-monitor/lxqt-config-monitor_autogen/EWIEGA46WW/moc_fastmenu.cpp:10,
[  176s]                  from /home/abuild/rpmbuild/BUILD/lxqt-config-1.2.0/build/lxqt-config-monitor/lxqt-config-monitor_autogen/mocs_compilation.cpp:2:
[  176s] /usr/include/KF5/KScreen/kscreen/config.h:197:32: error: 'std::optional' has not been declared
[  176s]   197 |     void adjustPriorities(std::optional<OutputPtr> keep = std::nullopt);
[  176s]       |                                ^~~~~~~~
[  176s] /usr/include/KF5/KScreen/kscreen/config.h:197:40: error: expected ',' or '...' before '<' token
[  176s]   197 |     void adjustPriorities(std::optional<OutputPtr> keep = std::nullopt);
[  176s]       |                                        ^
[  177s] make[2]: *** [lxqt-config-monitor/CMakeFiles/lxqt-config-monitor.dir/build.make:231: lxqt-config-monitor/CMakeFiles/lxqt-config-monitor.dir/lxqt-config-monitor_autogen/mocs_compilation.cpp.o] Error 1
```

This is on openSUSE Tumbleweed. How does it look in other rolling release distros?

**Comment by jubalh** [comment]
@stefonarch do you also have this on Arch?

**Comment by stefonarch** [comment]
I have atm  `plasma-framework-5.103.0-1  plasma-workspace-5.26.5-3` and no issue with compiling, full upgrade is running now.

**Comment by jubalh** [comment]
Thanks @Chiitoo ! I'll try that and then close this bug.
